# Generated by Django 5.1 on 2025-11-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Site Web'), ('ecommerce', 'E-commerce'), ('mobile', 'Application Mobile'), ('api', 'API / Backend'), ('other', 'Autre')], default='web', help_text='Catégorie du projet', max_length=20),
        ),
    ]
