# Generated by Django 5.1 on 2025-11-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_e96b08_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'featured'], name='portfolio_p_is_publ_2a5daa_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'order'], name='portfolio_p_is_publ_5064b5_idx'),
        ),
    ]
