# Generated by Django 5.1 on 2025-11-03 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_add_missing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', '-created_at'], name='quotes_quot_status_86add0_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['created_by', '-created_at'], name='quotes_quot_created_73e98a_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['signature_token'], name='quotes_quot_signatu_4863af_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='quotes_quot_quote_n_6770d1_idx'),
        ),
    ]
