# Generated by Django 5.1 on 2025-11-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Raison du refus'),
        ),
    ]
