# Generated by Django 5.1 on 2025-11-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_quotes_quot_status_86add0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(help_text='Identifiant URL-friendly', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description de la catégorie')),
                ('icon', models.CharField(blank=True, help_text="Classe CSS d'icône (ex: fas fa-globe)", max_length=50)),
                ('color', models.CharField(default='#2563eb', help_text='Couleur hexadécimale', max_length=7)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de projet',
                'verbose_name_plural': 'Catégories de projets',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='projecttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_types', to='quotes.projectcategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='supplementaryoption',
            name='compatible_categories',
            field=models.ManyToManyField(blank=True, help_text="Si vide, l'option est disponible pour toutes les catégories", related_name='compatible_options', to='quotes.projectcategory', verbose_name='Catégories compatibles'),
        ),
    ]
